// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTickets.Infrastructure.Data;

#nullable disable

namespace SupportTickets.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SupportTickets.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 1,
                            Description = "Password reset email never arrives after submitting the forgot-password form.",
                            Priority = 2,
                            Status = 0,
                            Title = "Cannot reset password"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 2,
                            Description = "Support dashboard KPI charts render empty in Safari 17; Chrome is fine.",
                            Priority = 1,
                            Status = 1,
                            Title = "Dashboard charts blank on Safari"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 3,
                            Description = "Clicking Download Invoice returns HTTP 500 for account ACCT-8891.",
                            Priority = 3,
                            Status = 2,
                            Title = "Invoice PDF download fails"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 1,
                            Description = "FAQ item 3 says 'reciept' instead of 'receipt'. Low urgency.",
                            Priority = 0,
                            Status = 3,
                            Title = "Typo on billing FAQ page"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 30, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 2,
                            Description = "Customer receives two identical ticket-update emails for every status change.",
                            Priority = 1,
                            Status = 4,
                            Title = "Duplicate notification emails"
                        });
                });

            modelBuilder.Entity("SupportTickets.Domain.Entities.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Reproduced on Safari 17.4. Looking at the Chart.js canvas init path.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 5,
                            TicketId = 2
                        },
                        new
                        {
                            Id = 2,
                            Body = "Root cause was a null invoice template id. Fix deployed to staging.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedById = 6,
                            TicketId = 3
                        });
                });

            modelBuilder.Entity("SupportTickets.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sam.customer@example.com",
                            Name = "Sam Customer",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "riley.customer@example.com",
                            Name = "Riley Customer",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "casey.customer@example.com",
                            Name = "Casey Customer",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "alex.agent@example.com",
                            Name = "Alex Agent",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "morgan.agent@example.com",
                            Name = "Morgan Agent",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "taylor.agent@example.com",
                            Name = "Taylor Agent",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "jordan.lead@example.com",
                            Name = "Jordan Lead",
                            Role = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "quinn.lead@example.com",
                            Name = "Quinn Lead",
                            Role = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "avery.admin@example.com",
                            Name = "Avery Admin",
                            Role = 3
                        },
                        new
                        {
                            Id = 10,
                            Email = "blake.admin@example.com",
                            Name = "Blake Admin",
                            Role = 3
                        });
                });

            modelBuilder.Entity("SupportTickets.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTickets.Domain.Entities.User", "AssignedTo")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SupportTickets.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SupportTickets.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("SupportTickets.Domain.Entities.User", "CreatedBy")
                        .WithMany("Comments")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTickets.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTickets.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SupportTickets.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
